
// 經典日常劇本 (針對肢體正確性優化版本)
export const stickerScenarios = [
  "嗨嗨 (Waving hello with one hand clearly raised, the other arm resting at side, exactly two arms total, normal fingers)",
  "謝啦 (Bowing politely with both hands placed neatly at sides, clear and fixed limb structure)",
  "讚喔 (Lifting RIGHT hand in a clear thumbs-up gesture, left arm remains at side, strictly two arms in total)",
  "哈哈哈 (Laughing joyfully with both hands holding its belly, symmetric arm placement)",
  "嗚嗚 (Crying loudly while using two hands to rub its eyes, clear and distinct arm structure)",
  "亨! (Crossing exactly two arms over the chest in a pouting angry pose, no extra limbs)",
  "衝啊 (Typing furiously on a laptop with two hands on the keyboard, clear arm-to-body connection)",
  "+1 (Standing with a large floating '+1' symbol next to it, both hands visible and resting naturally, normal anatomy)",
  "收到 (Giving a sharp salute with the right hand to the forehead, left arm at side, strictly two arms)",
  "晚安 (Sleeping while hugging a single pillow with two arms, clear limb structure)",
  "早安 (Stretching both arms upward, symmetric posture, exactly two arms and two legs)",
  "辛苦了 (Holding a small cup of tea with two hands, presenting it forward politely)",
  "好耶 (Enthusiastically clapping two hands together, clear arm movement)",
  "推推 (Giving a double thumbs up with both hands, symmetric arm placement, exactly ten fingers total)",
  "咦? (Tilting head with one hand touching the chin, the other arm folded, clear structure)",
  "嚇! (Shocked with both hands covering the mouth, eyes popping out, clear two-arm structure)",
  "羞 (Blushing with both hands covering its cheeks, simple and clear limb positions)",
  "餓了 (Drooling with both hands holding an empty bowl, clear arm anatomy)",
  "乾杯 (Lifting a single beer mug with the right hand, left arm at side)",
  "慶生 (Wearing a party hat, holding a small cake with two hands, symmetric pose)",
  "想一下 (One hand on chin, looking upward in thought, the other arm at side, no extra limbs)",
  "加油 (Waving two pom-poms in the air, one in each hand, symmetric and clear arm structure)",
  "抱抱 (Opening exactly two arms wide for a hug, clear and simple anatomy)",
  "愛你 (Making a finger heart sign with one hand close to the chest, other arm at side)",
  "求求你 (Pleading with both hands clasped together in front of the face, teary eyes)",
  "交給我 (Thumbs up with the right hand, pointing to self with the left hand, clear limb count)",
  "等下 (Holding up one hand in a 'stop' gesture, the other arm at side, strictly two arms)",
  "帥吧 (Posing with sunglasses, one hand on hip, the other hand pointing at the camera)",
  "略~ (Sticking tongue out, both hands pulling down lower eyelids in a playful 'Akanbe' pose)",
  "無言 (Standing still with both arms hanging at sides, dark lines over the head, two arms total)",
  "躺平 (Lying flat on the ground on its back, arms and legs spread clearly, exactly four limbs total)",
  "開飯 (Holding a fork in right hand and a knife in left hand, sitting at a table)",
  "對對對 (Nodding head vigorously, hands clapping together rhythmically)",
  "母湯 (Shaking head, crossing both arms in a big 'X' shape in front of the body)",
  "撒花 (Throwing flower petals with both hands, symmetric arm movement)",
  "熱血 (Pumping one fist in the air, the other arm at side, muscular and clear arm structure)",
  "跪求 (Prostrating on the floor, both arms extended forward on the ground, clear limb count)",
  "偷看 (Peeking from behind a wall, only one eye and one hand visible, clear body structure)"
];

// 魔性崩壞專用劇本 (同樣強化肢體數量約束)
export const abstractScenarios = [
  // 💼 職場生存篇
  "收到 (Copy): Standing stiff like a robot, giving a salute with one hand that is twice as big as the head, only two arms total.",
  "安排 (Plan): Drawing chaotic lines in the air with one hand, other hand on hip, strictly two arms.",
  "在路上 (Coming): Running posture but the two legs are transformed into bicycle wheels.",
  "會議中 (Meeting): Face is a clock, holding a pen with one hand, other hand on desk.",
  "已讀 (Seen): Two giant eyeballs floating, character's two hands holding a phone.",
  "趕件中 (Rush): Distorted character typing with two very long noodle-like arms on a keyboard.",
  "求放過 (Mercy): Kneeling with two hands clasped, eyes melting, strictly two arms.",
  "這鍋我不背 (Not me): Throwing a giant black pot over the shoulder with two hands.",
  "正在假裝忙 (Fake): Staring at a wall, holding one pen with one hand, only two arms.",
  "腦袋斷線 (Snapped): Plug dangling from head, two arms hanging limp at sides.",
  "靈魂下班 (Ghost): Ghost flying out, physical body sitting with two arms on chair.",
  "想退休 (Retire): Lying in a hammock, holding a drink with one hand, two legs visible.",
  "沒錢了 (Broke): Two hands pulling out empty pockets, crying soap bubbles.",
  "這很不專業 (Unpro): Wearing a suit, head is a clown nose, two arms crossed.",
  "明天再說 (Later): Pushing a giant rock with two hands, lazy expression.",
  "確認過眼神 (Eyes): One eye a camera, other a heart, two hands holding a magnifying glass.",
  "救命 (Help): Inside an hourglass, two hands pressing against the glass.",
  "加班中 (OT): Eyes glowing red, two hands typing so fast they are a blur.",
  "薪水小偷 (Thief): Sneaky raccoon look, two hands holding a sack.",
  "正在開機 (Booting): Wind-up key in back, two arms in a stiff T-pose.",
  "好的 (Fine): Wide smile, two hands giving two thumbs up, strictly two arms.",
  "報告難產 (Stuck): Trying to lay a USB egg, two hands holding the chair.",
  "請指示 (Order): Saluting a rubber duck with one hand, other arm at side.",
  "我太難了 (Hard): Squashed flat by a brick, two arms and two legs poking out from sides.",
  "又是星期一 (Mon): Melted into goo, two hands barely visible on the armrests.",

  // 🎓 校園日常篇
  "學分... (Credit): Chasing flying coins with two arms extended forward.",
  "會過嗎？ (Pass?): Balancing on a rope with two arms spread for balance.",
  "求歐趴 (All Pass): Worshipping a statue with two hands raised, symmetric pose.",
  "圖書館見 (Lib): Buried under books, one hand holding a highlighter poking out.",
  "沒睡飽 (Sleepy): Holding a pillow with two arms, eyes sagging.",
  "報告地獄 (Hell): Surrounded by demons, two hands protecting the head.",
  "腦容量不足 (Full): Head ballooning, two hands holding the large head.",
  "想下課 (Go): Body stretching toward door, two hands reaching forward.",
  "誰有點名？ (Roll): Hiding in a trash can, two hands holding the lid.",
  "分組求饒 (Team): Character splitting into three, each with two arms and two legs.",
  "老師別看我 (Shy): Turning transparent, two hands covering the face.",
  "又要重考 (Fail): Sitting in rain, two hands holding a '0' paper.",
  "正在吸收 (Study): Head is a sponge, two hands holding a book open.",
  "放棄思考 (Stop): Hamster wheel in head, two arms hanging limp.",
  "土地法難唸 (Law): Eating a book with two hands, teeth crumbling.",
  "PPT 沒靈感 (PPT): Staring at a black hole, two hands reaching out.",
  "這題我會 (I know): Head is a lightbulb, one hand raised high, other at side.",
  "才怪 (Psyche): Second face on back of head, two hands behind back.",
  "衝一波 (Go): Riding a pencil rocket with two hands gripping it.",
  "教授饒命 (Mercy): Prostrating on floor, two arms extended forward.",
  "沒筆記 (None): Holding one wilted flower pen with one hand, two arms total.",
  "考試爆炸 (Boom): Head exploding, two arms waving in panic.",
  "活著真累 (Tired): Dragging a heavy stone with two hands and a rope.",
  "需要能量 (Power): Plugged into outlet, two hands glowing.",
  "睡魔攻擊 (Attack): Hugged by a monster, two arms trying to push away.",

  // 🌈 社交與生活篇
  "蛤？ (What): Abstract face, two hands palms up in confusion.",
  "哈哈 (Haha): Giant mouth, two hands slapping knees in laughter.",
  "真的 (Real): Using a magnifying glass with one hand, other hand on hip.",
  "走起 (Let's go): Body is a skateboard, two hands as handlebars.",
  "吃什麼？ (Food): Rotating menu head, two hands holding stomach.",
  "不想動 (Lazy): Roots into sofa, two arms resting on cushions.",
  "懶 (Laze): Melted ice cream look, two hands poking out from the puddle.",
  "先不要 (No): Two hands creating an 'X' energy shield.",
  "被閃瞎 (Blind): Three sunglasses, two hands covering the eyes.",
  "求帶飛 (Carry): Grabbing a bird leg with two hands.",
  "我就廢 (Trash): Inside a trash bag, two hands holding a scepter.",
  "笑死 (Lol): Lying on ground in pieces, each arm clearly separated.",
  "真香 (Good): Long nose, two hands holding a fried chicken drumstick.",
  "傻眼 (Dumb): Eyes are marbles, two hands holding the face in shock.",
  "已羨慕 (Envy): Green face, two hands over the heart.",
  "邊緣人 (Alone): In a dark circle, two arms hugging its own knees.",
  "是在哈囉？ (Hello): Abstract face, one hand waving, other hand on hip.",
  "保持微笑 (Smile): Holding an emoji mask with one hand, other arm at side.",
  "我選宅 (Stay): Inside a blanket cocoon, two hands holding a phone.",
  "錢錢再見 (Money): Wallet flying away, two arms reaching out in despair.",
  "美食召喚 (Hungry): Floating zombie-like, two arms extended toward a burger.",
  "正在耍廢 (Idle): Juggling three pillows with two hands while lying down.",
  "沒救了 (Done): Cracked vase body, two hands holding a glue bottle.",
  "讚啦 (Great): Two hands giving thumbs up, thumbs are small smiley faces.",
  "先去洗澡 (Bath): Running trail, two hands holding a rubber duck."
];
