// 經典日常劇本 (適合精緻模式)
export const stickerScenarios = [
  "嗨嗨 (Waving hello)",
  "謝啦 (Bowing and saying thank you)",
  "讚喔 (Giving a thumbs up)",
  "哈哈哈 (Laughing joyfully)",
  "嗚嗚 (Crying loudly)",
  "亨! (Pouting and angry)",
  "衝啊 (Typing furiously on laptop)",
  "+1 (Standing with a large, stylish '+1' symbol floating next to the character)",
  "收到 (Giving a salute)",
  "晚安 (Sleeping with a pillow)",
  "早安 (Stretching with sun background)",
  "辛苦了 (Offering a cup of tea)",
  "好耶 (Clapping hands enthusiastically)",
  "推推 (Double thumbs up)",
  "咦? (Tilting head with question mark)",
  "嚇! (Shocked with eyes popping out)",
  "羞 (Blushing with hands on face)",
  "餓了 (Drooling over delicious food)",
  "乾杯 (Holding a beer mug or juice)",
  "慶生 (Birthday party with cake)",
  "想一下 (Hand on chin thinking)",
  "加油 (Waving pom-poms for cheer)",
  "抱抱 (Opening arms for a hug)",
  "愛你 (Making a finger heart sign)",
  "求求你 (Pleading with teary eyes)",
  "交給我 (Thumbs up with confidence)",
  "等下 (Holding up a hand to stop)",
  "帥吧 (Posing with sunglasses)",
  "略~ (Sticking tongue out playfully)",
  "無言 (Speechless with black lines)",
  "躺平 (Lying flat on the ground)",
  "開飯 (Holding fork and knife)",
  "對對對 (Nodding head vigorously)",
  "母湯 (Shaking head vigorously)",
  "撒花 (Throwing flower petals)",
  "熱血 (Pumping fist in the air)",
  "跪求 (Prostrating in formal apology)",
  "偷看 (Peeking from behind a corner)"
];

// 魔性崩壞專用劇本 (精選 75 組 - 職場/校園/社交)
export const abstractScenarios = [
  // 💼 職場生存篇 (25 組)
  "收到 (Copy): Standing stiff like a robot, giving a salute but the hand is twice as big as the head.",
  "安排 (Plan): Drawing chaotic, nonsensical floating lines in the air with a serious face.",
  "在路上 (Coming): Running posture but the legs are transformed into bicycle wheels.",
  "會議中 (Meeting): Face replaced by a large analog clock with hands spinning in reverse.",
  "已讀 (Seen): Two giant eyeballs floating in front of a smartphone, character is invisible.",
  "趕件中 (Rush): Six mismatched arms typing frantically on three floating keyboards.",
  "求放過 (Mercy): Kneeling with a puppy-eyed expression where the eyes are literally melting off the face.",
  "這鍋我不背 (Not me): Throwing a giant black cooking pot over the shoulder with a terrified look.",
  "正在假裝忙 (Fake): Staring intensely at a blank wall while holding a pen upside down.",
  "腦袋斷線 (Snapped): Top of head is off, and a literal electrical plug is dangling out.",
  "靈魂下班 (Ghost): Sitting at a desk while a translucent ghost version of the character flies out the window.",
  "想退休 (Retire): Lying in a hammock made of old documents, wearing a Hawaiian shirt and a diaper.",
  "沒錢了 (Broke): Pockets turned inside out, crying coins that instantly turn into soap bubbles.",
  "這很不專業 (Unpro): Wearing a suit but the head is replaced by a giant clown nose.",
  "明天再說 (Later): Pushing a giant 'Tomorrow' rock uphill with a very lazy, sleepy face.",
  "確認過眼神 (Eyes): One eye is a camera lens, the other is a literal heart, staring intensely.",
  "救命 (Help): Trapped inside a giant transparent hourglass filled with coffee beans.",
  "加班中 (OT): Eyes are bloodshot and glowing red, hair is standing up like fire, typing with toes.",
  "薪水小偷 (Thief): Sneaking away with a giant sack labeled 'SALARY', character looks like a sneaky raccoon.",
  "正在開機 (Booting): A literal wind-up key in the back of the character, turning slowly.",
  "好的 (Fine): A very wide, frozen smile with a 'Loading' bar above the head, eyes are blank.",
  "報告難產 (Stuck): Character trying to lay an egg that is actually a USB drive.",
  "請指示 (Order): Saluting a giant floating rubber duck with a military cap.",
  "我太難了 (Hard): Squashed flat by a giant falling brick labeled 'LIFE'.",
  "又是星期一 (Mon): Melted into a puddle of gray goo on a chair, with a calendar showing 'MONDAY'.",

  // 🎓 校園日常篇 (25 組)
  "學分... (Credit): Chasing after gold coins with 'A+' written on them that have wings and are flying away.",
  "會過嗎？ (Pass?): Balancing on a thin tightrope over a pit of burning textbooks.",
  "求歐趴 (All Pass): Worshipping a giant stone statue of a scholar, offering bubble tea as a sacrifice.",
  "圖書館見 (Lib): Buried under a mountain of books, only a single hand holding a highlighter is visible.",
  "沒睡飽 (Sleepy): Eyes sagging down to the floor like melted cheese, holding a pillow.",
  "報告地獄 (Hell): Surrounded by tiny demons holding laptops and pitchforks.",
  "腦容量不足 (Full): Head ballooning to 10x size, filled with colorful junk and floating question marks.",
  "想下課 (Go): Body is stretched toward the door like elastic, while the feet are stuck to the floor.",
  "誰有點名？ (Roll): Hiding inside a giant trash can with only the eyes peeking out.",
  "分組求饒 (Team): Character splitting into three mini-versions of itself to avoid people.",
  "老師別看我 (Shy): Turning into a semi-transparent ghost to blend into the classroom wall.",
  "又要重考 (Fail): Sitting in a rain cloud indoors, holding a test paper with a giant red '0'.",
  "正在吸收 (Study): Head is a literal sponge, someone is pouring a bucket of 'KNOWLEDGE' on it.",
  "放棄思考 (Stop): Brain replaced by a small, rotating hamster wheel with a tiny hamster inside.",
  "土地法難唸 (Law): Trying to eat a giant, dry book, teeth are crumbling into dust.",
  "PPT 沒靈感 (PPT): Staring at a screen that shows only a black hole sucking in the character.",
  "這題我會 (I know): Head glowing like a bright lightbulb, expression is overly confident and distorted.",
  "才怪 (Psyche): Character has a second face on the back of its head that is sticking its tongue out.",
  "衝一波 (Go): Riding on top of a giant pencil like it's a rocket ship.",
  "教授饒命 (Mercy): Prostrating on the floor, while the floor is turning into a swamp.",
  "沒筆記 (None): Holding a pen that has turned into a wilted flower, staring at a blank notebook.",
  "考試爆炸 (Boom): Head is literally exploding into colorful confetti and math formulas.",
  "活著真累 (Tired): Dragging a giant, heavy stone shaped like a sleeping face.",
  "需要能量 (Power): Character plugged into a wall outlet, eyes glowing yellow.",
  "睡魔攻擊 (Attack): A giant, fluffy purple monster is hugging the character tightly.",

  // 🌈 社交與生活篇 (25 組)
  "蛤？ (What): One eye is on the cheek, the other is on the forehead, mouth is a zig-zag line.",
  "哈哈 (Haha): Mouth takes up 90% of the face, teeth look like white piano keys jumping around.",
  "真的 (Real): Looking through a giant magnifying glass at a tiny grain of sand, face distorted.",
  "走起 (Let's go): Body is a skateboard, the character's head is the driver.",
  "吃什麼？ (Food): Head turning into a rotating menu of pizza, sushi, and noodles.",
  "不想動 (Lazy): Character has grown roots into the sofa, turning into a potato.",
  "懶 (Laze): Melted like a scoop of ice cream on the floor.",
  "先不要 (No): Both hands creating a giant 'X' shield made of energy.",
  "被閃瞎 (Blind): Wearing three pairs of sunglasses, looking at a bright glowing heart.",
  "求帶飛 (Carry): Grabbing onto the leg of a giant flying bird with a hopeful face.",
  "我就廢 (Trash): Sitting inside a literal trash bag with a crown on the head.",
  "笑死 (Lol): Character is lying on the ground, literally broken into several smiling pieces.",
  "真香 (Good): Smelling a floating fried chicken, nose has grown 10 inches long.",
  "傻眼 (Dumb): Eyes replaced by two white marble balls, jaw dropped to the floor.",
  "已羨慕 (Envy): Face turning green, eyes turning into green dollar signs or hearts.",
  "邊緣人 (Alone): Sitting in a dark circle while everyone else is in a bright party background.",
  "是在哈囉？ (Hello): One hand waving, while the face is a confused abstract painting.",
  "保持微笑 (Smile): Face is a static emoji mask, while the body behind it is crying.",
  "我選宅 (Stay): Wrapping self in a giant blanket cocoon, only eyes visible.",
  "錢錢再見 (Money): Wallet has grown wings and is flying into a dark vortex.",
  "美食召喚 (Hungry): Floating toward a giant hamburger like a zombie.",
  "正在耍廢 (Idle): Character juggling three pillows while lying down.",
  "沒救了 (Done): Character is a cracked vase being glued back together with honey.",
  "讚啦 (Great): Two thumbs up, but the thumbs are actually small smiley faces.",
  "先去洗澡 (Bath): Running away so fast it leaves a trail of soap bubbles and rubber ducks."
];