
// 經典日常劇本 (優化版本：不畫字，嚴格肢體約束)
export const stickerScenarios = [
  "嗨嗨 (Waving hello with one hand clearly raised, the other hand tucked behind its back, exactly two arms total)",
  "謝啦 (Bowing politely with both hands placed neatly at sides, clear and fixed limb structure)",
  "讚喔 (Lifting the RIGHT hand in a bold thumbs-up gesture, LEFT hand is strictly behind the back. Strictly only two arms total.)",
  "哈哈哈 (Laughing joyfully with both hands holding its belly, symmetric arm placement)",
  "嗚嗚 (Crying. Two hands are closed into fists and placed near the eyes. Strictly only two arms total.)",
  "亨! (Crossing exactly two arms tightly over the chest in a pouting angry pose. Strictly only two arms visible.)",
  "+1 (Standing next to a large floating PLUS ONE symbol, both hands resting naturally at sides, no extra limbs)",
  "收到 (Giving a military salute with the RIGHT hand, LEFT hand is straight down at the side. Strictly only two arms total.)",
  "晚安 (Sleeping while hugging a pillow with exactly two arms wrapped around it. Both hands visible on the pillow.)",
  "早安 (Stretching both arms upward, symmetric posture, exactly two arms and two legs)",
  "辛苦了 (Offering a cup with both hands, presenting it forward politely, stable limb structure)",
  "好耶 (Clapping two hands together, clear arm movement)",
  "推推 (Double thumbs up with both hands, symmetric arm placement, exactly ten fingers total)",
  "咦? (Tilting head with one hand touching the chin, the other hand behind back, clear structure)",
  "嚇! (Shocked. Two hands are pressed flat against the cheeks. Strictly two arms total.)",
  "羞 (Blushing with exactly two hands covering its cheeks. Clear and distinct two-arm structure.)",
  "餓了 (Drooling with both hands holding an empty bowl, clear arm anatomy)",
  "乾杯 (Lifting a mug with the right hand, left hand is behind back, strictly two arms total)",
  "生日快樂 (Wearing a party hat, holding a cake with both hands, symmetric and stable arm structure)",
  "想一下 (One hand on chin, looking upward, the other hand behind back, no extra limbs)",
  "加油 (Waving two pom-poms in the air, one in each hand, symmetric and clear arm structure)",
  "抱抱 (Opening exactly two arms wide for a hug, clear and simple anatomy)",
  "愛你 (Making a heart shape using exactly two hands held together in front of the chest. Strictly only two arms total.)",
  "求求你 (Pleading with both hands clasped together in front of the face. Clear and stable limb structure.)",
  "交給我 (Thumbs up with the right hand, left hand pointing to self, strictly two arms)",
  "等下 (Holding up one hand in a 'stop' gesture, the other hand behind back, strictly two arms)",
  "帥吧 (Posing with sunglasses, one hand on hip, the other hand behind back)",
  "略~ (Playfully pulling down lower eyelids with exactly two hands, strictly only two arms visible)",
  "無言 (Standing still with both arms hanging at sides, dark lines appearing over the head, two arms total)",
  "躺平 (Lying flat on the ground on its back, arms and legs spread clearly, exactly four limbs total)",
  "對對對 (Nodding head vigorously, hands clapping together rhythmically)",
  "母湯 (Shaking head, crossing both arms in a big 'X' shape in front of the body)",
  "撒花 (Throwing petals with both hands, symmetric arm movement)",
  "跪求 (Prostrating on the floor, both arms extended forward on the ground, clear limb count)",
  "偷看 (Peeking from behind a wall, only one hand visible, clear body structure)"
];

// 魔性崩壞專用劇本 (同樣強化肢體數量與禁字約束)
export const abstractScenarios = [
  "收到 (Copy): Standing stiff like a robot, giving a salute with one hand, other hand behind back, strictly two arms.",
  "安排 (Plan): Drawing lines in the air with one hand, other hand behind back, strictly two arms.",
  "在路上 (Coming): Running posture but the two legs are transformed into bicycle wheels, two arms for balance.",
  "會議中 (Meeting): Face is a clock, holding a pen with one hand, other hand behind back.",
  "已讀 (Seen): Two giant eyeballs floating, character's two hands holding a phone.",
  "趕件中 (Rush): Distorted character typing with two very long noodle-like arms on a keyboard.",
  "求放過 (Mercy): Kneeling with two hands clasped, eyes melting, strictly two arms.",
  "這鍋我不背 (Not me): Throwing a giant black pot over the shoulder with both hands.",
  "正在假裝忙 (Fake): Staring at a wall, holding one pen with one hand, other hand behind back.",
  "腦袋斷線 (Snapped): Plug dangling from head, two arms hanging limp at sides.",
  "靈魂下班 (Ghost): Ghost flying out, physical body sitting with two arms on chair.",
  "想退休 (Retire): Lying in a hammock, holding a drink with one hand, other hand behind back.",
  "沒錢了 (Broke): Two hands pulling out empty pockets, crying soap bubbles.",
  "這很不專業 (Unpro): Wearing a suit, head is a clown nose, two arms crossed.",
  "明天再說 (Later): Pushing a giant rock with both hands, lazy expression.",
  "救命 (Help): Inside an hourglass, two hands pressing against the glass.",
  "加班中 (OT): Eyes glowing red, two hands typing so fast they are a blur.",
  "薪水小偷 (Thief): Sneaky raccoon look, two hands holding a sack.",
  "好的 (Fine): Wide smile, two hands giving two thumbs up, strictly two arms.",
  "我太難了 (Hard): Squashed flat by a brick, two arms and two legs poking out from sides.",
  "又是星期一 (Mon): Melted into goo, two hands barely visible on the armrests.",
  "蛤？ (What): Abstract face, two hands palms up in confusion.",
  "哈哈 (Haha): Giant mouth, two hands slapping knees in laughter.",
  "吃什麼？ (Food): Head turning into a rotating menu, two hands holding a fork and knife.",
  "不想動 (Lazy): Character has grown roots into the sofa, two hands holding a remote.",
  "先不要 (No): Both hands creating a giant 'X' shield made of energy.",
  "被閃瞎 (Blind): Wearing three pairs of sunglasses, two hands covering eyes.",
  "我就廢 (Trash): Sitting inside a literal trash bag, two hands holding the opening.",
  "笑死 (Lol): Character broken into several smiling pieces, two hands visible.",
  "真香 (Good): Smelling a floating fried chicken, two hands reaching for it.",
  "傻眼 (Dumb): Eyes replaced by marble balls, two hands on cheeks.",
  "已羨慕 (Envy): Face turning green, two hands holding a green heart.",
  "是在哈囉？ (Hello): One hand waving, other hand behind back, confused face.",
  "我選宅 (Stay): Wrapping self in a blanket, two hands peeking out.",
  "錢錢再見 (Money): Wallet flying away, two hands reaching for it.",
  "美食召喚 (Hungry): Floating toward a burger, two hands extended.",
  "沒救了 (Done): Character is a cracked vase, two hands holding a glue stick.",
  "讚啦 (Great): Two thumbs up, but the thumbs are small smiley faces, strictly two arms."
];
